# Generated by Django 3.2 on 2022-08-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='sdata',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='scgpa',
            field=models.FloatField(max_length=10),
        ),
    ]
