# Generated by Django 3.2 on 2022-08-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220817_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.TextField(max_length=5)),
                ('academic_year', models.TextField(max_length=12)),
                ('department', models.TextField(max_length=20)),
                ('no_honours', models.IntegerField()),
                ('honours', models.TextField(max_length=300)),
                ('no_minors', models.IntegerField()),
                ('minors', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selected_Hm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=15)),
                ('shonours', models.TextField(max_length=300)),
                ('sminors', models.TextField(max_length=300)),
                ('honours_priority', models.IntegerField()),
                ('minors_priority', models.IntegerField()),
            ],
        ),
    ]
