# Generated by Django 3.2 on 2022-08-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hm_selected_hm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hm',
            name='honours',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minors',
        ),
    ]
