# Generated by Django 3.2 on 2022-08-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220819_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hm',
            name='academic_year',
            field=models.TextField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='hm',
            name='department',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hm',
            name='no_honours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hm',
            name='no_minors',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hm',
            name='regulation',
            field=models.TextField(blank=True, max_length=5),
        ),
    ]
