# Generated by Django 4.1 on 2022-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220819_1529'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='studentdata',
        #     name='sdept',
        #     field=models.CharField(default=0, max_length=30),
        #     preserve_default=False,
        # ),
    ]
