# Generated by Django 4.1 on 2022-08-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hm_honour1_hm_honour10_hm_honour2_hm_honour3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hm',
            name='honour1',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='honour10',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='honour2',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='honour3',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='honour4',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='honour5',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='honour6',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='honour7',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='honour8',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='honour9',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor1',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor10',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor2',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor3',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor4',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor5',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor6',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor7',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor8',
        ),
        migrations.RemoveField(
            model_name='hm',
            name='minor9',
        ),
    ]
