# Generated by Django 4.1 on 2022-08-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hm_honour1_hm_honour10_hm_honour2_hm_honour3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hm',
            name='honourmax1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmax10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmax2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmax3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmax4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmax5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmax6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmax7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmax8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmax9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='honourmin9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormax9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hm',
            name='minormin9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
