# Generated by Django 4.1 on 2022-08-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hm_honourmax1_hm_honourmax10_hm_honourmax2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_hm',
            name='honours_priority',
        ),
        migrations.RemoveField(
            model_name='selected_hm',
            name='minors_priority',
        ),
        migrations.RemoveField(
            model_name='selected_hm',
            name='shonours',
        ),
        migrations.RemoveField(
            model_name='selected_hm',
            name='sminors',
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='honour_priority9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='minor_priority9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour1',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour10',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour2',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour3',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour4',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour5',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour6',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour7',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour8',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='shonour9',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor1',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor10',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor2',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor3',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor4',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor5',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor6',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor7',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor8',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='sminor9',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='selected_hm',
            name='ssid',
            field=models.CharField(max_length=20),
        ),
    ]
