# Generated by Django 4.1 on 2022-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_selected_hm_honours_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected_hm',
            name='Hpriority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selected_hm',
            name='Mpriority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
